name: "Verify Docker Build"

on:
  pull_request:
    branches:
      - dev

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build only
        uses: docker/build-push-action@v5
        with:
          context: .
          # Importante: load=true compila la imagen en el demonio local
          # pero NO la sube a DockerHub.
          load: true
          tags: mmb-server:test
          # Esto asegura que el caché se use para ir rápido, igual que en tu otro action
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify binary exists
        run: |
          echo "La imagen se compiló correctamente. Verificando integridad..."
